### ISSUE TITLE
httplib.ResponseNotReady

### ISSUE THREAD

**Issue by stwktw** [googlesamples/android-play-publisher-api#13]
I've tried uploading the APK file .
But I failed to upload a file .
When I try to oauth2 authentication requests , I guess filtering on outbound firewall policy .
What is the port that you use ?

Error message is as follows:
# log.

Traceback (most recent call last):
  File "basic_list_apks.py", line 62, in <module>
    main(sys.argv)
  File "basic_list_apks.py", line 39, in main
    scope='https://www.googleapis.com/auth/androidpublisher')
  File "C:\Dev\Python27\lib\site-packages\googleapiclient\sample_tools.py", line
 89, in init
    credentials = tools.run_flow(flow, storage, flags)
  File "C:\Dev\Python27\lib\site-packages\oauth2client\util.py", line 132, in po
sitional_wrapper
    return wrapped(_args, *_kwargs)
  File "C:\Dev\Python27\lib\site-packages\oauth2client\tools.py", line 220, in r
un_flow
    credential = flow.step2_exchange(code, http=http)
  File "C:\Dev\Python27\lib\site-packages\oauth2client\util.py", line 132, in po
sitional_wrapper
    return wrapped(_args, *_kwargs)
  File "C:\Dev\Python27\lib\site-packages\oauth2client\client.py", line 1838, in
 step2_exchange
    headers=headers)
  File "C:\Dev\Python27\lib\site-packages\httplib2__init__.py", line 1593, in r
equest
    (response, content) = self._request(conn, authority, uri, request_uri, metho
d, body, headers, redirections, cachekey)
  File "C:\Dev\Python27\lib\site-packages\httplib2__init__.py", line 1335, in _
request
    (response, content) = self._conn_request(conn, request_uri, method, body, he
aders)
  File "C:\Dev\Python27\lib\site-packages\httplib2__init__.py", line 1291, in _
conn_request
    response = conn.getresponse()
  File "C:\Dev\Python27\lib\httplib.py", line 1018, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady

**Comment by vincentwyshan** [comment]
I have the same problem
