### ISSUE TITLE
The purchase token was not found.

### ISSUE THREAD

**Issue by anychen** [googlesamples/android-play-publisher-api#21]
I keep getting this exception. 
I make sure the purchaseToken is valid
严重: Exception was thrown while updating listing
com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "location" : "token",
    "locationType" : "parameter",
    "message" : "The purchase token was not found.",
    "reason" : "purchaseTokenNotFound"
  } ],
  "message" : "The purchase token was not found."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:1)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1049)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.play.developerapi.samples.CheckIabPurchased.main(CheckIabPurchased.java:82)

**Comment by anychen** [comment]
Most of the purchase verification will give a normal responce, few of them will give a responce of '' 404''

**Comment by anychen** [comment]
anybody  help me?how to slove it

**Comment by biokys** [comment]
Same problem last 2 days. It damages our production environment!

**Comment by cre8ivejp** [comment]
Same here we had 10 issues yesterday. But after a while they returned 200 response.

**Comment by psyh** [comment]
Also same problem last 2 days!

**Comment by DataGreed** [comment]
same problem, anyone got a solution so far?

**Comment by cre8ivejp** [comment]
I talked with a guy who works at Google yesterday. This problem will be fixed soon.
They were working on the servers yesterday and it affected the billing api.
In the app I work here is working fine again. 
For someone who is still getting this error, try to cancel the subscription (in my case) once and buy it again.

**Comment by DataGreed** [comment]
Seems like it started working today. @cre8ivejp thanks for the info! It would be great if they Google had some kind of a status page for issues like that
