### ISSUE TITLE
Java - GoogleJsonResponseException: 401 Unauthorized

### ISSUE THREAD

**Issue by pstha2017** [googlesamples/android-play-publisher-api#27]
Hi,
I am getting 401 Unauthorized exception while trying to run the java sample code with Service account.

Below is the error stack:

com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.play.developerapi.samples.ListApks.main(ListApks.java:55)

The service account was created and has been marked as the owner of the application.
Appreciate any kind of help here.

**Comment by ytianhui** [comment]
In google play console, 
open set Users & permissions menu,
set Users with expired access with correct date.

**Comment by astrolamb-gaming** [comment]
Have a similar issue:
`com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)`

Is this an issue with authorization somehow? Slightly thrown by the Json part of it.

**Comment by fattanasio** [comment]
Hi, I am administrator with no expire date but i get always GoogleJsonResponseException: 401 Unauthorized.
How can resolve it ? Thank you

**Comment by QuentinSc** [comment]
Hello,
Somebody succed to manage this ?

Thank you

**Comment by arindam-b** [comment]
Hello,

I am facing same error (from local machine) as well as from Kubernetes Cluster. Any wayout ?

Thanks.

**Comment by arindam-b** [comment]
I have fixed my issue, in the following way:

1. Service Account json (key.json) file added as kubectl secret.
2. During my pod spins up, I have put the content of the secret as key.json to a path, mounted in the same pod attached to it.
3. Then read the key.json from code, it works fine for me.

**Comment by spurgy** [comment]
Please help I'm having the same issue. @arindam-b I don't understand your solution. I'm not working on kubernetes but the prob is same.

**Comment by arindam-b** [comment]
@spurgy - you need to ensure when you access the specific resource, you pass proper credentials interns of service account.json file etc which you can generate . M
